spring.application.name=login-processing-service
server.port=8080

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=login-processing-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

kafka-save-login-event-business-topic=customer-login
kafka-save-login-event-client-topic=login-tracking-result

rest.track-login-service.url=http://localhost:8181
rest.track-login-service.track.login.path=/api/v1/login

rest.track-login-service.username=trackLogin
rest.track-login-service.password=trackLogin123

