spring.application.name=track-login-service

server.port=8181

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/track_login_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=validate
# Logging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.jdbc=INFO

